l=['caias',3+5j,21,56.8]
print("original list: ",l)
l.insert(0,2)
print("insert(0,2): ",l)
l.remove(3+5j)
print("remove(3+5j): ",l)
l.append("dog")
print("append(dog): ",l)
length=len(l)
print("Length of list: ",length)
l.pop(2)
print("pop(2): ",l)
l.clear()
print("Clear(): ",l)
